spring:
  cloud:
    azure:
      servicebus:
        namespace: ${asb.namespace}
#        connection-string: ${asb.conn.str}
        credential:
          client-id: ${cred.client.id}
          client-secret: ${cred.client.secret}
        profile:
          tenant-id: ${cred.tenantId}
    stream:
      function:
        definition: supply;
      bindings:
        supply-out-0:
          destination: ${asb.topic}
      servicebus:
        bindings:
          supply-out-0:
            producer:
              entity-type: topic
      poller:
        fixed-delay: 1000
        initial-delay: 0
server:
  port: 8081