$env:AZURE_SERVICEBUS_NAMESPACE=$(./terraform output -raw AZURE_SERVICEBUS_NAMESPACE)
$env:AZURE_SERVICEBUS_TOPIC_NAME=$(./terraform output -raw AZURE_SERVICEBUS_TOPIC_NAME)
$env:AZURE_SERVICEBUS_TOPIC_SUBSCRIPTION_NAME=$(./terraform output -raw AZURE_SERVICEBUS_TOPIC_SUBSCRIPTION_NAME)
$env:AZURE_SERVICEBUS_RESOURCE_GROUP=$(./terraform output -raw AZURE_SERVICEBUS_RESOURCE_GROUP)
$env:AZURE_SERVICEBUS_SUBSCRIPTION_ID=$(./terraform output -raw AZURE_SERVICEBUS_SUBSCRIPTION_ID)

Write-Output AZURE_SERVICEBUS_NAMESPACE=$env:AZURE_SERVICEBUS_NAMESPACE
Write-Output AZURE_SERVICEBUS_TOPIC_NAME=$env:AZURE_SERVICEBUS_TOPIC_NAME
Write-Output AZURE_SERVICEBUS_TOPIC_SUBSCRIPTION_NAME=$env:AZURE_SERVICEBUS_TOPIC_SUBSCRIPTION_NAME
Write-Output AZURE_SERVICEBUS_RESOURCE_GROUP=$env:AZURE_SERVICEBUS_RESOURCE_GROUP
Write-Output AZURE_SERVICEBUS_SUBSCRIPTION_ID=$env:AZURE_SERVICEBUS_SUBSCRIPTION_ID