spring:
  cloud:
    azure:
      servicebus:
        namespace: ${asb.namespace}
        #        connection-string: ${asb.conn.str}
        credential:
          client-id: ${cred.client.id}
          client-secret: ${cred.client.secret}
        profile:
          tenant-id: ${cred.tenantId}
    stream:
      function:
        definition: consume;
      bindings:
        consume-in-0:
          destination: ${asb.topic}
          group: ${asb.topic.subscription}
      servicebus:
        bindings:
          consume-in-0:
            consumer:
              auto-complete: false
      poller:
        fixed-delay: 1000
        initial-delay: 0
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others=true:
  datasource:
    url: jdbc:h2:file:./asbdemo
    username: asbdemo
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8081